/**
 * High-value X/Twitter account watchlist for market-moving intelligence.
 *
 * Only include genuinely influential accounts that are likely to move markets.
 * This is intentionally compact to keep the X filtered stream cheap and low-noise.
 */

export type XAccountTier = "TIER_1" | "TIER_2" | "TIER_3";

export type XMarketAccount = {
  username: string;
  /** Verified display name for dashboard/audit. */
  displayName: string;
  category: string;
  tier: XAccountTier;
  /** 0–1 influence weight. Tier 1 should dominate. */
  influenceScore: number;
  /** Asset symbols or keywords this account is known to affect. */
  assetsOfInterest: string[];
  enabled: boolean;
  notes?: string;
};

export const X_MARKET_WATCHLIST: XMarketAccount[] = [
  // TIER 1 — extreme market influence
  {
    username: "realDonaldTrump",
    displayName: "Donald Trump",
    category: "us_administration",
    tier: "TIER_1",
    influenceScore: 1.0,
    assetsOfInterest: ["SPY", "QQQ", "DELL", "INTC", "NVDA", "BTC", "USD"],
    enabled: true,
    notes: "Former US president; policy/company statements frequently move sectors and single names.",
  },
  {
    username: "POTUS",
    displayName: "President of the United States",
    category: "us_administration",
    tier: "TIER_1",
    influenceScore: 0.95,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC", "GLD"],
    enabled: true,
  },
  {
    username: "elonmusk",
    displayName: "Elon Musk",
    category: "ceo_influencer",
    tier: "TIER_1",
    influenceScore: 0.95,
    assetsOfInterest: ["TSLA", "BTC", "DOGE", "SPY"],
    enabled: true,
  },
  {
    username: "SecYellen",
    displayName: "Janet Yellen",
    category: "us_treasury",
    tier: "TIER_1",
    influenceScore: 0.9,
    assetsOfInterest: ["SPY", "QQQ", "USD", "GLD", "BTC"],
    enabled: true,
  },
  {
    username: "federalreserve",
    displayName: "Federal Reserve",
    category: "central_bank",
    tier: "TIER_1",
    influenceScore: 0.9,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC", "GLD"],
    enabled: true,
  },
  {
    username: "SECGov",
    displayName: "SEC",
    category: "regulator",
    tier: "TIER_1",
    influenceScore: 0.9,
    assetsOfInterest: ["BTC", "ETH", "SOL", "COIN", "SPY"],
    enabled: true,
  },
  {
    username: "cz_binance",
    displayName: "CZ",
    category: "exchange_ceo",
    tier: "TIER_1",
    influenceScore: 0.85,
    assetsOfInterest: ["BTC", "ETH", "BNB", "SOL"],
    enabled: true,
  },
  {
    username: "brian_armstrong",
    displayName: "Brian Armstrong",
    category: "exchange_ceo",
    tier: "TIER_1",
    influenceScore: 0.85,
    assetsOfInterest: ["COIN", "BTC", "ETH"],
    enabled: true,
  },
  {
    username: "saylor",
    displayName: "Michael Saylor",
    category: "crypto_founder",
    tier: "TIER_1",
    influenceScore: 0.85,
    assetsOfInterest: ["BTC", "MSTR"],
    enabled: true,
  },
  {
    username: "VitalikButerin",
    displayName: "Vitalik Buterin",
    category: "crypto_founder",
    tier: "TIER_1",
    influenceScore: 0.8,
    assetsOfInterest: ["ETH", "BTC"],
    enabled: true,
  },

  // TIER 2 — major corporate / industry influence
  {
    username: "NVIDIA",
    displayName: "NVIDIA",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.75,
    assetsOfInterest: ["NVDA", "SMCI", "AMD", "INTC"],
    enabled: true,
  },
  {
    username: "Apple",
    displayName: "Apple",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.75,
    assetsOfInterest: ["AAPL", "QQQ"],
    enabled: true,
  },
  {
    username: "Microsoft",
    displayName: "Microsoft",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.75,
    assetsOfInterest: ["MSFT", "QQQ"],
    enabled: true,
  },
  {
    username: "Amazon",
    displayName: "Amazon",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.7,
    assetsOfInterest: ["AMZN", "QQQ"],
    enabled: true,
  },
  {
    username: "Google",
    displayName: "Google",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.7,
    assetsOfInterest: ["GOOGL", "QQQ"],
    enabled: true,
  },
  {
    username: "Meta",
    displayName: "Meta",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.7,
    assetsOfInterest: ["META", "QQQ"],
    enabled: true,
  },
  {
    username: "Tesla",
    displayName: "Tesla",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.75,
    assetsOfInterest: ["TSLA", "QQQ"],
    enabled: true,
  },
  {
    username: "Intel",
    displayName: "Intel",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.65,
    assetsOfInterest: ["INTC", "NVDA", "AMD"],
    enabled: true,
  },
  {
    username: "AMD",
    displayName: "AMD",
    category: "company",
    tier: "TIER_2",
    influenceScore: 0.65,
    assetsOfInterest: ["AMD", "NVDA", "INTC"],
    enabled: true,
  },
  {
    username: "JPMorgan",
    displayName: "JPMorgan Chase",
    category: "bank",
    tier: "TIER_2",
    influenceScore: 0.65,
    assetsOfInterest: ["JPM", "SPY", "XLF"],
    enabled: true,
  },
  {
    username: "GoldmanSachs",
    displayName: "Goldman Sachs",
    category: "bank",
    tier: "TIER_2",
    influenceScore: 0.65,
    assetsOfInterest: ["GS", "SPY", "XLF"],
    enabled: true,
  },
  {
    username: "BankofAmerica",
    displayName: "Bank of America",
    category: "bank",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["BAC", "SPY", "XLF"],
    enabled: true,
  },
  {
    username: "MorganStanley",
    displayName: "Morgan Stanley",
    category: "bank",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["MS", "SPY", "XLF"],
    enabled: true,
  },
  {
    username: "PayPal",
    displayName: "PayPal",
    category: "payments",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["PYPL", "BTC"],
    enabled: true,
  },
  {
    username: "Block",
    displayName: "Block",
    category: "payments",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["SQ", "BTC"],
    enabled: true,
  },
  {
    username: "krakenfx",
    displayName: "Kraken",
    category: "exchange",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["BTC", "ETH"],
    enabled: true,
  },
  {
    username: "okx",
    displayName: "OKX",
    category: "exchange",
    tier: "TIER_2",
    influenceScore: 0.55,
    assetsOfInterest: ["BTC", "ETH"],
    enabled: true,
  },
  {
    username: "circle",
    displayName: "Circle",
    category: "stablecoin",
    tier: "TIER_2",
    influenceScore: 0.6,
    assetsOfInterest: ["USDC", "BTC", "ETH"],
    enabled: true,
  },

  // TIER 3 — information sources
  {
    username: "AP",
    displayName: "Associated Press",
    category: "news_wire",
    tier: "TIER_3",
    influenceScore: 0.7,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "Reuters",
    displayName: "Reuters",
    category: "news_wire",
    tier: "TIER_3",
    influenceScore: 0.7,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "Bloomberg",
    displayName: "Bloomberg",
    category: "news_wire",
    tier: "TIER_3",
    influenceScore: 0.7,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "CNBC",
    displayName: "CNBC",
    category: "news",
    tier: "TIER_3",
    influenceScore: 0.6,
    assetsOfInterest: ["SPY", "QQQ", "BTC"],
    enabled: true,
  },
  {
    username: "FinancialTimes",
    displayName: "Financial Times",
    category: "news",
    tier: "TIER_3",
    influenceScore: 0.65,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "WSJ",
    displayName: "Wall Street Journal",
    category: "news",
    tier: "TIER_3",
    influenceScore: 0.65,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "coindesk",
    displayName: "CoinDesk",
    category: "crypto_news",
    tier: "TIER_3",
    influenceScore: 0.6,
    assetsOfInterest: ["BTC", "ETH", "SOL"],
    enabled: true,
  },
  {
    username: "Cointelegraph",
    displayName: "Cointelegraph",
    category: "crypto_news",
    tier: "TIER_3",
    influenceScore: 0.55,
    assetsOfInterest: ["BTC", "ETH", "SOL"],
    enabled: true,
  },
  {
    username: "TheBlock__",
    displayName: "The Block",
    category: "crypto_news",
    tier: "TIER_3",
    influenceScore: 0.6,
    assetsOfInterest: ["BTC", "ETH", "SOL"],
    enabled: true,
  },
  {
    username: "decryptmedia",
    displayName: "Decrypt",
    category: "crypto_news",
    tier: "TIER_3",
    influenceScore: 0.5,
    assetsOfInterest: ["BTC", "ETH", "SOL"],
    enabled: true,
  },
  {
    username: "JoeWeisenthal",
    displayName: "Joe Weisenthal",
    category: "journalist",
    tier: "TIER_3",
    influenceScore: 0.55,
    assetsOfInterest: ["SPY", "QQQ", "BTC"],
    enabled: true,
  },
  {
    username: "lisaabramowicz1",
    displayName: "Lisa Abramowicz",
    category: "journalist",
    tier: "TIER_3",
    influenceScore: 0.55,
    assetsOfInterest: ["SPY", "QQQ", "USD", "BTC"],
    enabled: true,
  },
  {
    username: "nikhileshde",
    displayName: "Nikhilesh De",
    category: "journalist",
    tier: "TIER_3",
    influenceScore: 0.5,
    assetsOfInterest: ["BTC", "ETH"],
    enabled: true,
  },
];

export function enabledWatchlist(tierFilter?: XAccountTier): XMarketAccount[] {
  return X_MARKET_WATCHLIST.filter((a) => a.enabled && (!tierFilter || a.tier === tierFilter));
}

export function watchlistSummary() {
  return {
    total: X_MARKET_WATCHLIST.length,
    enabled: enabledWatchlist().length,
    tier1: enabledWatchlist("TIER_1").length,
    tier2: enabledWatchlist("TIER_2").length,
    tier3: enabledWatchlist("TIER_3").length,
  };
}
