/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestsRouteImport } from './routes/backtests'
import { Route as CopySignalsRouteImport } from './routes/copy-signals'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PolymarketRouteImport } from './routes/polymarket'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SocialRouteImport } from './routes/social'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as XIntelligenceRouteImport } from './routes/x-intelligence'
import { Route as TokenAssetIdRouteImport } from './routes/token.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsRoute = BacktestsRouteImport.update({
  id: '/backtests',
  path: '/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const CopySignalsRoute = CopySignalsRouteImport.update({
  id: '/copy-signals',
  path: '/copy-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymarketRoute = PolymarketRouteImport.update({
  id: '/polymarket',
  path: '/polymarket',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const XIntelligenceRoute = XIntelligenceRouteImport.update({
  id: '/x-intelligence',
  path: '/x-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenAssetIdRoute = TokenAssetIdRouteImport.update({
  id: '/token/$assetId',
  path: '/token/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/copy-signals': typeof CopySignalsRoute
  '/events': typeof EventsRoute
  '/learning': typeof LearningRoute
  '/news': typeof NewsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper': typeof PaperRoute
  '/polymarket': typeof PolymarketRoute
  '/scanner': typeof ScannerRoute
  '/social': typeof SocialRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
  '/training': typeof TrainingRoute
  '/wallets': typeof WalletsRoute
  '/x-intelligence': typeof XIntelligenceRoute
  '/token/$assetId': typeof TokenAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/copy-signals': typeof CopySignalsRoute
  '/events': typeof EventsRoute
  '/learning': typeof LearningRoute
  '/news': typeof NewsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper': typeof PaperRoute
  '/polymarket': typeof PolymarketRoute
  '/scanner': typeof ScannerRoute
  '/social': typeof SocialRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
  '/training': typeof TrainingRoute
  '/wallets': typeof WalletsRoute
  '/x-intelligence': typeof XIntelligenceRoute
  '/token/$assetId': typeof TokenAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/copy-signals': typeof CopySignalsRoute
  '/events': typeof EventsRoute
  '/learning': typeof LearningRoute
  '/news': typeof NewsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/paper': typeof PaperRoute
  '/polymarket': typeof PolymarketRoute
  '/scanner': typeof ScannerRoute
  '/social': typeof SocialRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
  '/training': typeof TrainingRoute
  '/wallets': typeof WalletsRoute
  '/x-intelligence': typeof XIntelligenceRoute
  '/token/$assetId': typeof TokenAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtests'
    | '/copy-signals'
    | '/events'
    | '/learning'
    | '/news'
    | '/opportunities'
    | '/paper'
    | '/polymarket'
    | '/scanner'
    | '/social'
    | '/strategies'
    | '/system'
    | '/training'
    | '/wallets'
    | '/x-intelligence'
    | '/token/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtests'
    | '/copy-signals'
    | '/events'
    | '/learning'
    | '/news'
    | '/opportunities'
    | '/paper'
    | '/polymarket'
    | '/scanner'
    | '/social'
    | '/strategies'
    | '/system'
    | '/training'
    | '/wallets'
    | '/x-intelligence'
    | '/token/$assetId'
  id:
    | '__root__'
    | '/'
    | '/backtests'
    | '/copy-signals'
    | '/events'
    | '/learning'
    | '/news'
    | '/opportunities'
    | '/paper'
    | '/polymarket'
    | '/scanner'
    | '/social'
    | '/strategies'
    | '/system'
    | '/training'
    | '/wallets'
    | '/x-intelligence'
    | '/token/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestsRoute: typeof BacktestsRoute
  CopySignalsRoute: typeof CopySignalsRoute
  EventsRoute: typeof EventsRoute
  LearningRoute: typeof LearningRoute
  NewsRoute: typeof NewsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PaperRoute: typeof PaperRoute
  PolymarketRoute: typeof PolymarketRoute
  ScannerRoute: typeof ScannerRoute
  SocialRoute: typeof SocialRoute
  StrategiesRoute: typeof StrategiesRoute
  SystemRoute: typeof SystemRoute
  TrainingRoute: typeof TrainingRoute
  WalletsRoute: typeof WalletsRoute
  XIntelligenceRoute: typeof XIntelligenceRoute
  TokenAssetIdRoute: typeof TokenAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests': {
      id: '/backtests'
      path: '/backtests'
      fullPath: '/backtests'
      preLoaderRoute: typeof BacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-signals': {
      id: '/copy-signals'
      path: '/copy-signals'
      fullPath: '/copy-signals'
      preLoaderRoute: typeof CopySignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymarket': {
      id: '/polymarket'
      path: '/polymarket'
      fullPath: '/polymarket'
      preLoaderRoute: typeof PolymarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x-intelligence': {
      id: '/x-intelligence'
      path: '/x-intelligence'
      fullPath: '/x-intelligence'
      preLoaderRoute: typeof XIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$assetId': {
      id: '/token/$assetId'
      path: '/token/$assetId'
      fullPath: '/token/$assetId'
      preLoaderRoute: typeof TokenAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestsRoute: BacktestsRoute,
  CopySignalsRoute: CopySignalsRoute,
  EventsRoute: EventsRoute,
  LearningRoute: LearningRoute,
  NewsRoute: NewsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PaperRoute: PaperRoute,
  PolymarketRoute: PolymarketRoute,
  ScannerRoute: ScannerRoute,
  SocialRoute: SocialRoute,
  StrategiesRoute: StrategiesRoute,
  SystemRoute: SystemRoute,
  TrainingRoute: TrainingRoute,
  WalletsRoute: WalletsRoute,
  XIntelligenceRoute: XIntelligenceRoute,
  TokenAssetIdRoute: TokenAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
